baseURL = "/"
title = "Introduction to Machine Learning on HPC"

theme = ["reveal-hugo"]

[markup.goldmark.renderer]
unsafe = true
  [markup.goldmark.parser.attribute]
  block = true  
  title = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
theme = "robot-lung"
slide_number = true
preview_links = true